
server:
  port: 8085
elasticjob:
  regCenter:
    #zookeeper 的ip:port
    serverLists: 127.0.0.1:2181
    #名命空间，自己定义就好了
    namespace: e-job1
  jobs:
    #你的这个定时任务名称，自定义名称
    myElasticJob:
      #定时任务的全路径名
      elasticJobClass: com.example.elasticdemo.job.MyJob1
      #定时任务执行的cron表达式
      cron: 0/10 * * * * ?
      #分片数量
      shardingTotalCount: 3
      shardingItemParameters: "0=北京,1=上海,2=深圳"
    occurErrorNoticeEmailJob:
      elasticJobClass: com.example.elasticdemo.job.SpringBootOccurErrorNoticeEmailJob
      overwrite: true
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      jobErrorHandlerType: EMAIL
      jobBootstrapBeanName: occurErrorNoticeEmailBean
      props:
        email:
          host: smtp.qq.com
          port: 465
          username: 1043253434@qq.com
          password: wsmarabeibtk
          useSsl: true
          subject: ElasticJob error message
          from: 10432534@qq.com
          to: 187202277@163.com
          cc: 187202277@163.com
          bcc: 187202277@163.com
          debug: false
